package com.funnel.keep.decorator;

public class Constants {
	
	// SYNCH
	private static final String SECURE_HOST = "https://";
	private static final String BASE_URL_LOCAL = "mainfunnel.com/KeepSafeServices";
	private static final String SERVICE_ENDPOINT = "/KeepSafeService.svc";

	public static String getServerUrl() {
		StringBuilder sb = new StringBuilder();

		sb.append(SECURE_HOST);

		sb = new StringBuilder(SECURE_HOST);
		sb.append(BASE_URL_LOCAL);

		sb.append(SERVICE_ENDPOINT);
		return sb.toString();
	}

	// REQUEST STATUS
	public static final int HANDLER_SUCCESS = 0;
	public static final int HANDLER_FAILURE = 1;
	public static final int STATUS_SUCCESS = 200;
	public static final int WRONG_EMAIL_OR_DISPLAYNAME = 101;
	public static final int WRONG_EMAIL_FORMAT = 102;
	public static final int SERVER_ERROR = 500;
	public static final int NO_VALID_GOOGLE_PLAY_SERVICS_APK_FOUND = 9901;
	public static final int DUPLICATED_BROWSER_ID = 598;

	// LOCAL REQUEST STATUS
	public static final int LOCAL_STATUS_MAIN_IMAGE_DOES_NOT_EXSIT = 888;
	public static final int LOCAL_STATUS_SUCCESS = 909;
	public static final int LOCAL_STATUS_FAILURE = 707;

	// SHARED_PREFERENCE
	public static final String KEY_SHARED_PREFERENCE_IMAGE = "KEY_SHARED_PREFERENCE_IMAGE";
	public static final String KEY_SHARED_PREFERENCE_AUTO_EXIT = "KEY_SHARED_PREFERENCE_AUTO_EXIT";
	public static final String KEY_SHARED_PREFERENCE_SHOULD_TOGGLE_AUTO_EXIT = "KEY_SHARED_PREFERENCE_SHOULD_TOGGLE_AUTO_EXIT";
	public static final String KEY_SHARED_PREFERENCE_LAST_UPDATE_DATE = "KEY_SHARED_PREFERENCE_LAST_UPDATE_DATE";
	public static final String KEY_SHARED_PREFERENCE_EMAIL = "KEY_SHARED_PREFERENCE_EMAIL";
	public static final String KEY_SHARED_PREFERENCE_LAST_RESTORE_DATE = "KEY_SHARED_PREFERENCE_LAST_RESTORE_DATE";
	public static final String KEY_SHARED_PREFERENCE_RESTORE_BIT = "KEY_SHARED_PREFERENCE_RESTORE_BIT";
	public static final String KEY_SHARED_PREFERENCE_UPDATE_BIT = "KEY_SHARED_PREFERENCE_UPDATE_BIT";

	// BROADCAST_KEYS
	public static final String BROADCAST_KEY_RELOAD_PASSWORDS = "BROADCAST_KEY_RELOAD_PASSWORDS";
	public static final String BROADCAST_KEY_RELOAD_WEB_TEXTS = "BROADCAST_KEY_RELOAD_WEB_TEXTS";
	public static final String BROADCAST_NOTIFICATION_TOAST = "BROADCAST_NOTIFICATION_TOAST";
	public static final String BROADCAST_TOAST_EXTRA_KEY = "BROADCAST_TOAST_EXTRA_KEY";
	public static final String BROADCAST_KEY_RELOAD_PICTURES = "BROADCAST_KEY_RELOAD_PICTURES";
	public static final String BROADCAST_KEY_RELOAD_NOTES = "BROADCAST_KEY_RELOAD_NOTES";
	public static final String BROADCAST_KEY_RELOAD_PASSWORDS_CATEGORIES_PAGE = "BROADCAST_KEY_RELOAD_PASSWORDS_CATEGORIES_PAGE";
	public static final String BROADCAST_KEY_RELOAD_PICTURES_CATEGORIES_PAGE = "BROADCAST_KEY_RELOAD_PICTURES_CATEGORIES_PAGE";
	public static final String BROADCAST_KEY_RELOAD_NOTES_CATEGORIES_PAGE = "BROADCAST_KEY_RELOAD_NOTES_CATEGORIES_PAGE";
	public static final String BROADCAST_KEY_RELOAD_SPECIFIC_PASSWORD_CATEGORIES_PAGE = "BROADCAST_KEY_RELOAD_SPECIFIC_PASSWORD_CATEGORIES_PAGE";
	public static final String BROADCAST_KEY_RELOAD_SPECIFIC_NOTE_CATEGORIES_PAGE = "BROADCAST_KEY_RELOAD_SPECIFIC_NOTE_CATEGORIES_PAGE";
	public static final String BROADCAST_KEY_RESTORE_DATA = "BROADCAST_KEY_RESTORE_DATA";

	// FRAGMENT NEW INSTANCE
	public static final String FRAGMENT_NEW_INSTANCE_CATEGORY_TITLE = "FRAGMENT_NEW_INSTANCE_CATEGORY_TITLE";
	public static final String FRAGMENT_NEW_INSTANCE_URI_IMAGE_POSITION = "FRAGMENT_NEW_INSTANCE_URI_IMAGE_POSITION";
	public static final String FRAGMENT_NEW_INSTANCE_ALBUM_TITLE = "FRAGMENT_NEW_INSTANCE_ALBUM_TITLE";
	public static final String FRAGMENT_NEW_INSTANCE_ALBUM_ID = "FRAGMENT_NEW_INSTANCE_ALBUM_ID";
	public static final String FRAGMENT_NEW_INSTANCE_ALBUM_SIZE = "FRAGMENT_NEW_INSTANCE_ALBUM_SIZE";
	public static final String FRAGMENT_NEW_INSTANCE_CATEGORY_ID = "FRAGMENT_NEW_INSTANCE_CATEGORY_ID";
	public static final String FRAGMENT_NEW_INSTANCE_NOTE_ID = "FRAGMENT_NEW_INSTANCE_NOTE_ID";
	public static final String FRAGMENT_NEW_INSTANCE_NOTE_TYPE = "FRAGMENT_NEW_INSTANCE_NOTE_TYPE";
	public static final String FRAGMENT_NEW_INSTANCE_PASSWORD_ID = "FRAGMENT_NEW_INSTANCE_PASSWORD_ID";
	public static final String FRAGMENT_NEW_INSTANCE_PASSWORD_ACCOUNT = "FRAGMENT_NEW_INSTANCE_PASSWORD_ACCOUNT";
	public static final String FRAGMENT_NEW_INSTANCE_PASSWORD_TEXT = "FRAGMENT_NEW_INSTANCE_PASSWORD_TEXT";
	public static final String FRAGMENT_NEW_INSTANCE_PASSWORD_USERNAME = "FRAGMENT_NEW_INSTANCE_PASSWORD_USERNAME";
	public static final String FRAGMENT_NEW_INSTANCE_PASSWORD_DESCRIPTION = "FRAGMENT_NEW_INSTANCE_PASSWORD_DESCRIPTION";
	public static final String FRAGMENT_NEW_INSTANCE_PASSWORD_BG_COLOR = "FRAGMENT_NEW_INSTANCE_PASSWORD_BG_COLOR";
	public static final String FRAGMENT_NEW_INSTANCE_NEW_PASSWORD = "FRAGMENT_NEW_INSTANCE_NEW_PASSWORD";
	public static final String FRAGMENT_NEW_INSTANCE_BACKUP = "FRAGMENT_NEW_INSTANCE_BACKUP";
	
	// INTENT
	public static final String INTENT_ENCRYPTION_KEY = "INTENT_ENCRYPTION_KEY";
	public static final String INTENT_VIEW_PAGER_START_POSITION = "INTENT_VIEW_PAGER_START_POSITION";
	public static final String INTENT_WEB_ID = "INTENT_WEB_ID";
	public static final int INTENT_SELECT_PICTURE = 12;
	public static final int INTENT_QR_COD_SCANNER = 13;
	
	// APPLICATION SETTINGS
	public static final int PASSWORD_MIN_LENGHT = 8;
	public static final int NONEXISTENT_NOTE_ID = -10;
	public static final int NOTE_BG_COLOR_ONE = 1;
	public static final int NOTE_BG_COLOR_TWO = 2;
	public static final int NOTE_BG_COLOR_THREE = 3;

	
}